### ISSUE TITLE
Usage with a password protected Netlify website

### ISSUE THREAD

**Issue by gslama-akqa** [JakePartusch/wait-for-netlify-action#4]
Hi there,

First thank you for this project!

My question is about password protected websites.
Any idea how we could use this with a Netlify instance that has Site-wide protection?

Other option, does it make sense to use basic auth with the login and password as part of the site name?

**Comment by JakePartusch** [comment]
Great suggestion! I think that we could most likely support this with an extra config variable. Maybe something like `auth_header`? 

We would then send the GET request with the header populated with the given data (eg. "Basic YWRtaW46aHVudGVyMg==").

**Comment by gslama-akqa** [comment]
Thanks for the quick answer Jake. That'd be ideal!

**Comment by JakePartusch** [comment]
Cool 👍 @gslama-akqa if you'd like to take a shot at a PR, I'd gladly accept. Otherwise, it might be a bit before I can get this implemented.
